version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    # restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: robocritic
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db_scripts/initial_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
