# Generated by Django 5.1.1 on 2024-09-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='platformgame',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reviewcon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reviewpro',
            options={'managed': False},
        ),
    ]
