# Generated by Django 5.1.1 on 2024-09-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0002_alter_game_options_alter_platform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
        migrations.AlterModelTable(
            name='platform',
            table='platform',
        ),
        migrations.AlterModelTable(
            name='platformgame',
            table='platform_game',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='reviewcon',
            table='review_con',
        ),
        migrations.AlterModelTable(
            name='reviewer',
            table='reviewer',
        ),
        migrations.AlterModelTable(
            name='reviewpro',
            table='review_pro',
        ),
    ]
