# Generated by Django 5.1.1 on 2024-09-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0003_alter_game_table_alter_platform_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False, 'ordering': ['-release_date']},
        ),
    ]
