# Generated by Django 5.1.1 on 2024-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0005_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
