# Generated by Django 5.1.1 on 2024-11-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0006_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
