# Generated by Django 5.1.1 on 2024-11-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0007_delete_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-release_date']},
        ),
    ]
