# Generated by Django 5.1.1 on 2024-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0008_alter_game_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
