# Generated by Django 5.1.1 on 2024-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0009_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='youtube_gameplay_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
