# Generated by Django 5.1.1 on 2024-11-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0010_game_youtube_gameplay_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False, 'ordering': ['-release_date']},
        ),
    ]
