# Generated by Django 5.1.1 on 2024-11-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0011_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
    ]
