# Generated by Django 5.1.1 on 2024-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0012_alter_game_options_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='game',
            name='critic_score_average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
