# Generated by Django 5.1.1 on 2024-11-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0013_alter_publisher_options_game_critic_score_average'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False, 'ordering': ['-release_date']},
        ),
    ]
