# Generated by Django 5.1.1 on 2024-11-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0014_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
    ]
