# Generated by Django 5.1.1 on 2024-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0015_alter_publisher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='rating_scale',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
