# Generated by Django 5.1.1 on 2024-11-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0016_publisher_rating_scale_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'managed': False},
        ),
    ]
