# Generated by Django 4.2.16 on 2024-11-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("robocritic", "0017_alter_publisher_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platformgame",
            options={},
        ),
    ]
