# Generated by Django 4.2.16 on 2024-11-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("robocritic", "0018_alter_platformgame_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="reviewcon",
            options={},
        ),
        migrations.AlterModelOptions(
            name="reviewpro",
            options={},
        ),
        migrations.AlterField(
            model_name="platformgame",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="robocritic.game"
            ),
        ),
        migrations.AlterField(
            model_name="platformgame",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
