# Generated by Django 5.1.1 on 2024-12-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0020_alter_platformgame_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-release_date']},
        ),
    ]
