# Generated by Django 5.1.1 on 2024-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0021_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
