# Generated by Django 5.1.1 on 2024-12-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robocritic', '0022_game_normalized_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False, 'ordering': ['-release_date']},
        ),
    ]
