ALTER TABLE game
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE game
    MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE genre
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE genre_game
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE platform
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE platform_game
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE publisher
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE publisher
    MODIFY created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE review
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE review
    MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE review_con
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE review_pro
    MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;

