[tool.poetry]
name = "etl"
version = "0.1.0"
description = ""
authors = ["Nate P <nlpruitt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mysql-connector-python = "^9.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
